services:
  aurora:
    image: marcinx98x/aurora-server:latest
    build: .
    container_name: aurora-server
    restart: unless-stopped
    ports:
      - "18000:8000"
    env_file:
      - .env
    volumes:
      - ./cache:/app/cache
      - ./data:/app/data
